--- #YAML:1.0
name:               XML-Parser-Lite-Tree-XPath
version:            0.24
abstract:           ~
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::More:           0
    XML::Parser::Lite::Tree:  0.11
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
