# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         XML-Parser-Lite-Tree-XPath
version:      0.22
version_from: lib/XML/Parser/Lite/Tree/XPath.pm
installdirs:  site
requires:
    XML::Parser::Lite::Tree:       0.06

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
